# Cambrian.jl settings
d_fitness: 1
n_population: 10
n_elite: 1
n_gen: 30
log_gen: 1
save_gen: 5
m_rate: 0.1
# MTCGP.jl settings
rows: 3
columns: 100
out_m_rate: 0.3
functions:
  - f_add
  - f_subtract
  - f_mult
  - f_abs
  - f_exp
  - f_sin
  - f_lt
  - f_gt
